from cave import Cave

cavern = Cave("cavern")
cavern.set_description("A dank and dirty cave")
dungeon1 = Cave("Dungeon chamber 1")
dungeon1.set_description("A large cave with a rack")
grotto = Cave("grotto")
grotto.set_description("A samll cave with ancient graffiti")
startcave = Cave("Start cave")
startcave.set_description("You are in a small cave with one exit")
mossyTunnel = Cave("mossy tunnel")
mossyTunnel.set_description("A tunnel lined with a variety of different mosses")
smallCliff = Cave("small cliff")
smallCliff.set_description("A small east facing cliff")
puddle = Cave("puddle")
puddle.set_description("A muddy pit at the bottom of the cliff")
mushroomTunnel = Cave("mushroom tunnel")
mushroomTunnel.set_description("A long tunnel filled with mushrooms")
crossroads = Cave("crossroads")
crossroads.set_description("A tunnel that splits into two directions")
dungeon2 = Cave("Dungeon chamber 2")
dungeon2.set_description("A smooth stoned room with dart traps")
crystalCavern = Cave("crystal cavern")
crystalCavern.set_description("A large cave with crystals protruding from the walls and ceiling")
tallCliff = Cave("tall cliff")
tallCliff.set_description("A tall cliff that overlooks a sump")
sump = Cave("sump")
sump.set_description("A small cave that collects water")
bridge = Cave("bridge")
bridge.set_description("A rickety bridge just above the crossroads")
dungeon3 = Cave("Dungeon chamber 3")
dungeon3.set_description("A long room with hair all over the floor")
wumpusLair = Cave("Wumpus lair")
wumpusLair.set_description("The lair of the mighty Wumpus!")

cavern.link_cave(dungeon, "south")
grotto.link_cave(dungeon, "east")
dungeon.link_cave(grotto, "west")
dungeon.link_cave(cavern, "north")
current_cave = cavern
while True:
    print("\n")
    current_cave.get_details()
    command = input("> ")
    current_cave = current_cave.move(command)