from cave import Cave


cavern = Cave("cavern")
cavern.set_description("A dank and dirty cave")
dungeon1 = Cave("Dungeon chamber 1")
dungeon1.set_description("A large cave with a rack")
grotto = Cave("grotto")
grotto.set_description("A samll cave with ancient graffiti")
startcave = Cave("Start cave")
startcave.set_description("You are in a small cave with one exit")
mossyTunnel = Cave("mossy tunnel")
mossyTunnel.set_description("A tunnel lined with a variety of different mosses")
smallCliff = Cave("small cliff")
smallCliff.set_description("A small east facing cliff")
puddle = Cave("puddle")
puddle.set_description("A muddy pit at the bottom of the cliff")
mushroomTunnel = Cave("mushroom tunnel")
mushroomTunnel.set_description("A long tunnel filled with mushrooms")
crossroads = Cave("crossroads")
crossroads.set_description("A tunnel that splits into two directions")
dungeon2 = Cave("Dungeon chamber 2")
dungeon2.set_description("A smooth stoned room with dart traps")
crystalCavern = Cave("crystal cavern")
crystalCavern.set_description("A large cave with penises protruding from the walls and ceiling")
tallCliff = Cave("tall cliff")
tallCliff.set_description("A tall cliff that overlooks a sump")
sump = Cave("sump")
sump.set_description("A small cave that collects water")
bridge = Cave("bridge")
bridge.set_description("A rickety bridge just above the crossroads")
dungeon3 = Cave("Dungeon chamber 3")
dungeon3.set_description("A long room with hair all over the floor")
wumpusLair = Cave("Wumpus lair")
wumpusLair.set_description("The lair of the mighty Wumpus!")

startcave.link_cave(cavern, "north")
cavern.link_cave(mossyTunnel, "east")
cavern.link_cave(smallCliff, "west")
cavern.link_cave(crossroads, "north")
smallCliff.link_cave(cavern, "west")
smallCliff.link_cave(dungeon1, "north")
smallCliff.link_cave(puddle, "east")
puddle.link_cave(mushroomTunnel, "north")
mushroomTunnel.link_cave(puddle, "south")
mushroomTunnel.link_cave(dungeon1, "west")
dungeon1.link_cave(mushroomTunnel, "east")
dungeon1.link_cave(smallCliff, "south")
dungeon1.link_cave(crossroads, "west")
crossroads.link_cave(dungeon1, "east")
crossroads.link_cave(cavern, "south")
crossroads.link_cave(dungeon2, "west")
mossyTunnel.link_cave(cavern, "east")
mossyTunnel.link_cave(dungeon2, "north")
dungeon2.link_cave(crossroads, "east")
dungeon2.link_cave(mossyTunnel, "south")
dungeon2.link_cave(crystalCavern, "west")
crystalCavern.link_cave(grotto, "south")
crystalCavern.link_cave(dungeon2, "east")
crystalCavern.link_cave(tallCliff, "north")
grotto.link_cave(crystalCavern, "north")
tallCliff.link_cave(crystalCavern, "south")
tallCliff.link_cave(sump, "east")
sump.link_cave(dungeon2, "south")
sump.link_cave(bridge, "east")
bridge.link_cave(sump, "west")
bridge.link_cave(crossroads, "south")
bridge.link_cave(dungeon3, "east")
dungeon3.link_cave(bridge, "west")
dungeon3.link_cave(wumpusLair, "east")




current_cave = startcave
while True:
    print("\n")
    current_cave.describe()
    current_cave.get_details()
    command = input("> ")
    current_cave = current_cave.move(command)